<a href="https://colab.research.google.com/github/tal21-linares/curso-ia-para-economia/blob/main/Taller_importaci%C3%B3n_y_extracci%C3%B3n_de_datos_Talia_Linares_David_Velandia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)

In [ ]:
!pip install xlrd

Requirement already satisfied: xlrd in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [ ]:
import requests
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving weoapr2024all.xls to weoapr2024all.xls

In [ ]:
import pandas as pd

weo_df = pd.read_csv("weoapr2024all.xls", sep="\t", encoding="latin1")

weo_df.head()

,W,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
weo_df.head()
weo_df.tail(10)
weo_df.sample(3)
weo_df.iloc[1:5,1]
len(weo_df)
weo_df.shape
weo_df.columns
weo_df.dtypes
weo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17252 entries, 0 to 17251
Data columns (total 61 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   W            0 non-null      float64
 1   Unnamed: 1   0 non-null      float64
 2   Unnamed: 2   0 non-null      float64
 3   Unnamed: 3   0 non-null      float64
 4   Unnamed: 4   0 non-null      float64
 5   Unnamed: 5   0 non-null      float64
 6   Unnamed: 6   0 non-null      float64
 7   Unnamed: 7   0 non-null      float64
 8   Unnamed: 8   0 non-null      float64
 9   Unnamed: 9   0 non-null      float64
 10  Unnamed: 10  0 non-null      float64
 11  Unnamed: 11  0 non-null      float64
 12  Unnamed: 12  0 non-null      float64
 13  Unnamed: 13  0 non-null      float64
 14  Unnamed: 14  0 non-null      float64
 15  Unnamed: 15  0 non-null      float64
 16  Unnamed: 16  0 non-null      float64
 17  Unnamed: 17  0 non-null      float64
 18  Unnamed: 18  0 non-null      float64
 19  Unnamed: 19  0 non-null      float64
 20  Unnamed: 20  0 non-null      float64
 21  Unnamed: 21  0 non-null      float64
 22  Unnamed: 22  0 non-null      float64
 23  Unnamed: 23  0 non-null      float64
 24  Unnamed: 24  0 non-null      float64
 25  Unnamed: 25  0 non-null      float64
 26  Unnamed: 26  0 non-null      float64
 27  Unnamed: 27  0 non-null      float64
 28  Unnamed: 28  0 non-null      float64
 29  Unnamed: 29  0 non-null      float64
 30  Unnamed: 30  0 non-null      float64
 31  Unnamed: 31  0 non-null      float64
 32  Unnamed: 32  0 non-null      float64
 33  Unnamed: 33  0 non-null      float64
 34  Unnamed: 34  0 non-null      float64
 35  Unnamed: 35  0 non-null      float64
 36  Unnamed: 36  0 non-null      float64
 37  Unnamed: 37  0 non-null      float64
 38  Unnamed: 38  0 non-null      float64
 39  Unnamed: 39  0 non-null      float64
 40  Unnamed: 40  0 non-null      float64
 41  Unnamed: 41  0 non-null      float64
 42  Unnamed: 42  0 non-null      float64
 43  Unnamed: 43  0 non-null      float64
 44  Unnamed: 44  0 non-null      float64
 45  Unnamed: 45  0 non-null      float64
 46  Unnamed: 46  0 non-null      float64
 47  Unnamed: 47  0 non-null      float64
 48  Unnamed: 48  0 non-null      float64
 49  Unnamed: 49  0 non-null      float64
 50  Unnamed: 50  0 non-null      float64
 51  Unnamed: 51  0 non-null      float64
 52  Unnamed: 52  0 non-null      float64
 53  Unnamed: 53  0 non-null      float64
 54  Unnamed: 54  0 non-null      float64
 55  Unnamed: 55  0 non-null      float64
 56  Unnamed: 56  0 non-null      float64
 57  Unnamed: 57  0 non-null      float64
 58  Unnamed: 58  0 non-null      float64
 59  Unnamed: 59  0 non-null      float64
 60  Unnamed: 60  0 non-null      float64
dtypes: float64(61)
memory usage: 8.0 MB

In [ ]:
url = "https://api.worldbank.org/v2/country/COL;ECU;BRA;CHL;MEX;PER/indicator/FP.CPI.TOTL.ZG?date=2010:2023&format=json"

response = requests.get(url)
data = response.json()

In [ ]:
records = data[1]

inflacion_df = pd.DataFrame([{
    "pais": r["country"]["value"],
    "anio": r["date"],
    "inflacion": r["value"]
} for r in records])

df.head()

     pais  anio  inflacion
0  Brazil  2023   4.593563
1  Brazil  2022   9.280106
2  Brazil  2021   8.301660
3  Brazil  2020   3.211768
4  Brazil  2019   3.732976

In [ ]:
inflacion_df = inflacion_df.sort_values(["pais","anio"])

In [ ]:
inflacion_df.head()

      pais  anio  inflacion
13  Brazil  2010   5.038727
12  Brazil  2011   6.636450
11  Brazil  2012   5.403499
10  Brazil  2013   6.204311
9   Brazil  2014   6.329040

In [ ]:
inflacion_df.tail(10)

        pais  anio  inflacion
29  Colombia  2022  10.177231
28  Colombia  2023  11.735904
49   Ecuador  2016   1.728265
48   Ecuador  2017   0.417336
47   Ecuador  2018  -0.224103
46   Ecuador  2019   0.266013
45   Ecuador  2020  -0.338872
44   Ecuador  2021   0.133251
43   Ecuador  2022   3.466170
42   Ecuador  2023   2.215688

In [ ]:
inflacion_df.sample(3)

        pais  anio  inflacion
33  Colombia  2018   3.240569
15     Chile  2022  11.643867
11    Brazil  2012   5.403499

In [ ]:
inflacion_df.iloc[1:5,1]

12    2011
11    2012
10    2013
9     2014
Name: anio, dtype: object

In [ ]:
len(inflacion_df)

50

In [ ]:
inflacion_df.shape

(50, 3)

In [ ]:
inflacion_df.columns

Index(['pais', 'anio', 'inflacion'], dtype='object')

In [ ]:
inflacion_df.dtypes

pais          object
anio          object
inflacion    float64
dtype: object

In [ ]:
inflacion_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 13 to 42
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pais       50 non-null     object
 1   anio       50 non-null     object
 2   inflacion  50 non-null     float64
dtypes: float64(1), object(2)
memory usage: 3.6+ KB

In [ ]:
indicadores = {
    "crecimiento_pib":"NY.GDP.MKTP.KD.ZG",
    "pib_per_capita_ppa":"NY.GDP.PCAP.PP.KD",
    "inflacion":"FP.CPI.TOTL.ZG",
    "desempleo":"SL.UEM.TOTL.ZS",
    "poblacion":"SP.POP.TOTL"
}

In [ ]:
dataframes = []

for nombre, codigo in indicadores.items():

    url = f"https://api.worldbank.org/v2/country/DEU/indicator/{codigo}?date=2010:2023&format=json"

    response = requests.get(url)
    data = response.json()[1]

    df_temp = pd.DataFrame([{
        "anio": r["date"],
        nombre: r["value"]
    } for r in data])

    dataframes.append(df_temp)

In [ ]:
alemania_df = dataframes[0]

for df in dataframes[1:]:
    alemania_df = alemania_df.merge(df, on="anio")

In [ ]:
alemania_df.head()

   anio  crecimiento_pib  pib_per_capita_ppa  inflacion  desempleo  poblacion
0  2023        -0.869648        63039.371970   5.946437      3.071   83287273
1  2022         1.809258        63676.087822   6.872574      3.137   83177813
2  2021         3.910000        62530.765320   3.066667      3.594   83196078
3  2020        -4.131914        60203.289760   0.144878      3.881   83160871
4  2019         0.977735        62849.374187   1.445660      3.163   83092962

In [ ]:
alemania_df.head()
alemania_df.tail(10)
alemania_df.sample(3)
alemania_df.iloc[1:5,1]
len(alemania_df)
alemania_df.shape
alemania_df.columns
alemania_df.dtypes
alemania_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   anio                14 non-null     object
 1   crecimiento_pib     14 non-null     float64
 2   pib_per_capita_ppa  14 non-null     float64
 3   inflacion           14 non-null     float64
 4   desempleo           14 non-null     float64
 5   poblacion           14 non-null     int64
dtypes: float64(4), int64(1), object(1)
memory usage: 804.0+ bytes

In [ ]:
url = "https://www.datos.gov.co/resource/gt2j-8ykr.csv"

colombia_df = pd.read_csv(url)

colombia_df.head()

,fecha_reporte_web,id_de_caso,fecha_de_notificaci_n,departamento,departamento_nom,ciudad_municipio,ciudad_municipio_nom,edad,unidad_medida,sexo,...,pais_viajo_1_cod,pais_viajo_1_nom,recuperado,fecha_inicio_sintomas,fecha_muerte,fecha_diagnostico,fecha_recuperado,tipo_recuperacion,per_etn_,nom_grupo_
0,2020-12-24 00:00:00,1556979,2020-12-22 00:00:00,76,VALLE,76001,CALI,67,1,F,...,NaN,NaN,Recuperado,2020-12-21 00:00:00,NaN,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6,NaN
1,2020-12-24 00:00:00,1556980,2020-12-19 00:00:00,76,VALLE,76001,CALI,66,1,F,...,NaN,NaN,Recuperado,2020-12-07 00:00:00,NaN,2020-12-23 00:00:00,2020-12-25 00:00:00,Tiempo,6,NaN
2,2020-12-24 00:00:00,1556981,2020-12-19 00:00:00,76,VALLE,76001,CALI,68,1,F,...,NaN,NaN,Recuperado,2020-12-18 00:00:00,NaN,2020-12-22 00:00:00,2021-01-01 00:00:00,Tiempo,6,NaN
3,2020-12-24 00:00:00,1556982,2020-12-22 00:00:00,76,VALLE,76001,CALI,74,1,F,...,NaN,NaN,Fallecido,2020-12-17 00:00:00,2020-12-30 00:00:00,2020-12-23 00:00:00,NaN,NaN,6,NaN
4,2020-12-24 00:00:00,1556983,2020-12-22 00:00:00,76,VALLE,76001,CALI,65,1,F,...,NaN,NaN,Recuperado,2020-12-21 00:00:00,NaN,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6,NaN

In [ ]:
colombia_df.head()
colombia_df.tail(10)
colombia_df.sample(3)
colombia_df.iloc[1:5,1]

len(colombia_df)
colombia_df.shape
colombia_df.columns
colombia_df.dtypes
colombia_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   fecha_reporte_web      1000 non-null   object
 1   id_de_caso             1000 non-null   int64
 2   fecha_de_notificaci_n  1000 non-null   object
 3   departamento           1000 non-null   int64
 4   departamento_nom       1000 non-null   object
 5   ciudad_municipio       1000 non-null   int64
 6   ciudad_municipio_nom   1000 non-null   object
 7   edad                   1000 non-null   int64
 8   unidad_medida          1000 non-null   int64
 9   sexo                   1000 non-null   object
 10  fuente_tipo_contagio   1000 non-null   object
 11  ubicacion              994 non-null    object
 12  estado                 994 non-null    object
 13  pais_viajo_1_cod       0 non-null      float64
 14  pais_viajo_1_nom       0 non-null      float64
 15  recuperado             996 non-null    object
 16  fecha_inicio_sintomas  985 non-null    object
 17  fecha_muerte           41 non-null     object
 18  fecha_diagnostico      1000 non-null   object
 19  fecha_recuperado       961 non-null    object
 20  tipo_recuperacion      961 non-null    object
 21  per_etn_               1000 non-null   int64
 22  nom_grupo_             13 non-null     object
dtypes: float64(2), int64(6), object(15)
memory usage: 179.8+ KB

In [ ]:
url = "https://api.worldbank.org/v2/country/all/indicator/SP.POP.TOTL?date=2010:2023&format=json"

response = requests.get(url)
data = response.json()[1]

poblacion_df = pd.DataFrame([{
    "pais": r["country"]["value"],
    "anio": r["date"],
    "poblacion": r["value"]
} for r in data])

In [ ]:
poblacion_df.head()
poblacion_df.tail()
poblacion_df.sample()
poblacion_df.iloc()
len(poblacion_df)
poblacion_df.shape
poblacion_df.columns
poblacion_df.dtypes
poblacion_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pais       50 non-null     object
 1   anio       50 non-null     object
 2   poblacion  50 non-null     int64
dtypes: int64(1), object(2)
memory usage: 1.3+ KB